/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import algo.ListaCircular;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import utilidades.CargadorDeTurnos;

/**
 *
 * @author fbarg
 */
public class TurnosGUI extends javax.swing.JFrame {

    private ListaCircular listaTurnos; // Esta clase la desarrollan los estudiantes
    private boolean adelante = true;
    private boolean desdeActual = false;


    /**
     * Creates new form TurnosGUI
     */
    public TurnosGUI() {
        initComponents();
        setLocationRelativeTo(null);

        this.listaTurnos = new ListaCircular();
        CargadorDeTurnos.cargarDesdeArchivo(listaTurnos, "turnos", this);

        String actual = (String) listaTurnos.obtenerActual();
        turnoActualLabel.setText("Turno Actual: " + (actual != null ? actual : "Ninguno"));

        actualizarTablaTurnos();

        turnoActualLabel.setHorizontalAlignment(SwingConstants.CENTER);
        turnoActualLabel.setFont(new Font("Arial", Font.BOLD, 18));
    }
//Se modifico
    private void actualizarTablaTurnos() {
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Turnos");

        if (listaTurnos.estaVacia()) {
            modelo.addRow(new Object[]{"(lista vacía)"});
            TablaTurnos.setModel(modelo);
            turnoActualLabel.setText("Turno Actual: Ninguno");
            return;
        }

        for (Object turno : (desdeActual
                ? listaTurnos.obtenerDesdeActual()
                : listaTurnos.obtenerTodos(adelante))) {

            modelo.addRow(new Object[]{turno});
        }

        TablaTurnos.setModel(modelo);
        SwingUtilities.invokeLater(() -> enfocarTurnoEnTabla());
    }


    private void enfocarTurnoEnTabla() {
        String turnoActual = (String) listaTurnos.obtenerActual();
        if (turnoActual == null) {
            return;
        }

        for (int i = 0; i < TablaTurnos.getRowCount(); i++) {
            String valor = (String) TablaTurnos.getValueAt(i, 0);
            if (turnoActual.equals(valor)) {
                TablaTurnos.setRowSelectionInterval(i, i); // Selecciona fila
                TablaTurnos.scrollRectToVisible(TablaTurnos.getCellRect(i, 0, true)); // Hace scroll si es necesario
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        turnoActualLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTurnos = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnSeguirActual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next.png"))); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/previous.png"))); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        turnoActualLabel.setText("Turno Actual:");

        TablaTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaTurnos);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/recycling.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profits.png"))); // NOI18N
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnSeguirActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profits.png"))); // NOI18N
        btnSeguirActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguirActualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turnoActualLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addGap(43, 43, 43)
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente)
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear)
                    .addComponent(btnOrder)
                    .addComponent(btnSeguirActual))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turnoActualLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeguirActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nuevoTurno = JOptionPane.showInputDialog(this, "Ingrese el nombre del turno:");
        if (nuevoTurno != null && !nuevoTurno.trim().isEmpty()) {
            listaTurnos.agregarTurno(nuevoTurno.trim());
            JOptionPane.showMessageDialog(this, "Turno agregado: " + nuevoTurno);

            // Guardar automáticamente
            CargadorDeTurnos.guardarEnArchivo(listaTurnos, "turnos");

            turnoActualLabel.setText("Turno Actual: " + listaTurnos.obtenerActual());
            actualizarTablaTurnos();
            enfocarTurnoEnTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre válido.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed
    private void anteriorSiguiente(boolean siguiente) {
        if (listaTurnos.estaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay turnos registrados.");
            return;
        }

        turnoActualLabel.setText("Turno Actual: "
                + (String) (siguiente ? listaTurnos.avanzar() : listaTurnos.retroceder()));

        enfocarTurnoEnTabla();
    }


    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
         anteriorSiguiente(!adelante);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
         anteriorSiguiente(adelante);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Deseas borrar todos los turnos?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            listaTurnos = new ListaCircular();
            CargadorDeTurnos.guardarEnArchivo(listaTurnos, "turnos");
            actualizarTablaTurnos();
            turnoActualLabel.setText("Turno Actual: Ninguno");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    
    
    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        if (listaTurnos.estaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay turnos en la lista.");
            return;
        }
        adelante = !adelante;
        actualizarTablaTurnos();

        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource(adelante ? "/icons/profits.png" : "/icons/loss.png")));
        btnOrder.setToolTipText(adelante ? "Orden normal" : "Orden inverso");

        String mensaje = adelante ? "Ordenado de inicio a fin." : "Ordenado de fin a inicio.";
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_btnOrderActionPerformed

    //Se modifico
    
    private void btnSeguirActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguirActualActionPerformed
        if (listaTurnos.estaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay turnos en la lista.");
            return;
        }

        desdeActual = !desdeActual;

        actualizarTablaTurnos();

        btnSeguirActual.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(desdeActual ? "/icons/loss.png" : "/icons/profits.png")));

        btnSeguirActual.setToolTipText(desdeActual
                ? "Mostrando desde el turno actual"
                : "Mostrar en orden normal");

        JOptionPane.showMessageDialog(this,
                desdeActual ? "Orden desde el turno actual." : "Orden normal de turnos.");
    }//GEN-LAST:event_btnSeguirActualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TurnosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TurnosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TurnosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TurnosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("No se pudo aplicar FlatLaf.");
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TurnosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaTurnos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnSeguirActual;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel turnoActualLabel;
    // End of variables declaration//GEN-END:variables
}
